### ISSUE TITLE
böyle bi hata veriyor..':app:validateDebugKeySigning'

### ISSUE THREAD

**Issue by ismly** [metinkale38/namaz-vakti-android#31]
Error:Execution failed for task ':app:validateDebugKeySigning'.
> Keystore file /home/metin/Daten/Dropbox/Dokumente/Sonstiges/debug.keystore not found for signing config 'debugKey'.

sorun ne olabilir?

**Comment by metinkale38** [comment]
build.gradle icerisinde signingConfigs bölümünü simeniz/ düzeltmeniz yeterli olacaktir
